

kind: SecurityContextConstraints
apiVersion: v1
metadata:
  name: test-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- admin
groups:
- admin-group
