apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend
spec:
  selector:
    matchLabels:
      app: server
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: server
        tier: backend
    spec: 
      containers:
        - name: server
          image: muzairs/classroom:backend-latest
          ports:
            - name: http
              containerPort: 80

