apiVersion: v1
kind: Service
metadata: 
  name: front-svc
spec:
  type: LoadBalancer
  selector:
    app: dashboard
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  