apiVersion: v1
kind: Service
metadata: 
  name: front-svc
spec:
  type: NodePort
  selector:
    app: dashboard
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

  