apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: dashboard-ingress
   annotations:
     nginx.ingress.kubernetes.io/rewrite-target: /$1
spec: 
  rules:
  - host: dashboard.com
    http:
      paths:
      - pathType: Prefix
        path: /login
        backend:
          service:
            name: classroom-api
            port:
              number: 80