apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
   name: dashboard-ingress
   annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /$1
spec: 
  rules:
    - host: class.com
      http:
        paths:
          - backend:
              service:
                name: front-svc
                port:
                  number: 80
            path: /
            pathType: "Prefix"